jenkins:
  numExecutors: 0
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  labelString: "master-node"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${tpl_JENKINS_WEB_UI_ADMIN_USER}
          password: ${tpl_JENKINS_WEB_UI_ADMIN_PASSWD}
          properties:
          - mailer:
              emailAddress: ${tpl_JENKINS_WEB_UI_ADMIN_EMAIL}
  nodes:
  - permanent:
      labelString: "gcp-agent"
      launcher:
        ssh:
          credentialsId: "ssh_private_key_to_connect_to_${tpl_JENKINS_AGENT_NAME}"
          host: ${tpl_JENKINS_AGENT_IP_ADDR}
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      name: "jenkins-ssh-agent-${tpl_JENKINS_AGENT_NAME}-GCE-Bootstrap-1"
      nodeDescription: "SSH Jenkins Agent ${tpl_JENKINS_AGENT_NAME}"
      numExecutors: 1
      remoteFS: ${tpl_JENKINS_AGENT_REMOTE_DIR}
      retentionStrategy: "always"
  - permanent:
      labelString: "gcp-agent"
      launcher:
        ssh:
          credentialsId: "ssh_private_key_to_connect_to_${tpl_JENKINS_AGENT_NAME}"
          host: 10.3.0.6
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      name: "jenkins-ssh-agent-${tpl_JENKINS_AGENT_NAME}-333"
      nodeDescription: "SSH Jenkins Agent ${tpl_JENKINS_AGENT_NAME} 333"
      numExecutors: 1
      remoteFS: ${tpl_JENKINS_AGENT_REMOTE_DIR}
      retentionStrategy: "always"
  - permanent:
      labelString: "gcp-agent"
      launcher:
        ssh:
          credentialsId: "ssh_private_key_to_connect_to_${tpl_JENKINS_AGENT_NAME}"
          host: 10.3.0.4
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      name: "jenkins-ssh-agent-${tpl_JENKINS_AGENT_NAME}-444"
      nodeDescription: "SSH Jenkins Agent ${tpl_JENKINS_AGENT_NAME} 444"
      numExecutors: 1
      remoteFS: ${tpl_JENKINS_AGENT_REMOTE_DIR}
      retentionStrategy: "always"
jobs:
  - script: >
      multibranchPipelineJob('terraform-jenkins-create-demo') {
        factory {
          workflowBranchProjectFactory {
            scriptPath('example-pipelines/example-create/Jenkinsfile')
          }
        }
        branchSources {
          github {
            id('12312313')
            scanCredentialsId('github-token')
            repoOwner("${tpl_GITHUB_USERNAME}")
            repository("${tpl_GITHUB_REPO_NAME}")
            buildOriginBranchWithPR(false)
            buildOriginBranch(true)
            buildOriginPRMerge(true)
            buildForkPRMerge(true)
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(10)
          }
        }
        triggers {
          periodic(1)
        }
      }
  - script: >
      pipelineJob('pipeline') {
      agent { label 'gcp-agent​' }
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/caleonardo/jenkins-pipeline-test-01' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: ${tpl_GITHUB_USERNAME}
              password: ${tpl_GITHUB_TOKEN}
              description: "Github personal token to connect to the repository."
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "ssh_private_key_to_connect_to_${tpl_JENKINS_AGENT_NAME}"
              username: jenkins
              description: "SSH private key to connect to jenkins-ssh-agent-${tpl_JENKINS_AGENT_NAME}"
              privateKeySource:
                directEntry:
                  privateKey: |
                    ${tpl_RSA_PRIVATE_KEY}